version: '3'

volumes:
  local_data: {}
  local_backups: {}
  local_gradle_dependencies: {}
  root_gradle_dependencies: {}
  local_vscode_extensions: {}

services:
  spring:
    build:
      context: .
      dockerfile: ./compose/local/spring/Dockerfile
      args:
        USERNAME: vscode
        USER_GROUP_NAME: workspace
        USER_UID: 1019
        USER_GID: 1019
    image: parse_logs_local_java
    container_name: parse_logs_local_java
    depends_on:
      - mysql
    volumes:
      - .:/app:z
      - local_gradle_dependencies:/home/vscode/.gradle/caches
      - root_gradle_dependencies:/root/.gradle/caches
      - local_vscode_extensions:/home/vscode/.vscode-server/extensions
    env_file:
      - ./.envs/.local/.spring
    ports:
      - '8080:8080'
    command: ["sleep", "infinity"]

  mysql:
    build:
      context: .
      dockerfile: ./compose/production/mysql/Dockerfile
    image: parse_logs_local_mysql
    container_name: parse_logs_local_mysql
    volumes:
      - local_data:/var/lib/mysql
      - local_backups:/backups
    ports:
      - '3306:3306'
    env_file:
      - ./.envs/.local/.mysql